version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"   # Location of package.json
    schedule:
      interval: "weekly"  # Check for updates every week
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - your-github-username
